# Generated by Django 5.2.3 on 2025-06-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'is_medico': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_medico', to='usuarios.usuariocliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'is_cliente': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_paciente', to='usuarios.usuariocliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos.sala'),
        ),
    ]
